#!/usr/bin/env bash

CURRENT_DIR=$(pwd)
PROJECT_DIR="$(cd ../ && pwd)"

# get options
P=$(sed -e 's#.*\-p=\([^\-]*\).*#\1#' <<< "$1$2$3$4$5")
C=$(sed -e 's#.*\-c=\([^\-]*\).*#\1#' <<< "$1$2$3$4$5")
V=$(sed -e 's#.*\-v=\([^\-]*\).*#\1#' <<< "$1$2$3$4$5")
M=$(sed -e 's#.*\-m=\([^\-]*\).*#\1#' <<< "$1$2$3$4$5")
L=$(sed -e 's#.*\-l=\([^\-]*\).*#\1#' <<< "$1$2$3$4$5")

# defaults
PHP_VERSION=7.4
DB_IMAGE=mariadb:10.5.8
LARAVEL_VERSION=8.*

## p
if [ ! "$P" == "$1$2$3$4$5" ]; then
    WEB_PORT=$P
fi

## v (PHP)
if [ ! "$V" == "$1$2$3$4$5" ]; then
    PHP_VERSION=$V
fi

## m (db_image)
if [ ! "$M" == "$1$2$3$4$5" ]; then
    DB_IMAGE=$M
fi

## c for create database
# update dockerlocal & add port if applicable
./install-git-submodules
cd ../DockerLocal
# We can be on master now
# git checkout -b PHP-7.4 origin/PHP-7.4 | grep 'exists' &> /dev/null
# git checkout PHP-7.4

# Setup DockerLocal
## PORT
if [ ! "$WEB_PORT" == "" ]; then
    echo "${WEB_PORT}" > port
fi

## VERSION (PHP)
if [ ! "$PHP_VERSION" == "" ]; then
    echo "${PHP_VERSION}" > versions/override-php-version
fi
## VERSION (PHP)
if [ ! "$DB_IMAGE" == "" ]; then
    echo "${DB_IMAGE}" > versions/override-db-image
fi

## web-server-root (for laravel, relative to dockerlocal web container)
echo "/var/www/site/app/public" > "web-server-root"

# Run DockerLocal
cd commands

# Copy site-tinker && make it executable
cp "$CURRENT_DIR/site-tinker" ./ && chmod +x site-tinker

# Copy site-artisan && make it executable
cp "$CURRENT_DIR/site-artisan" ./ && chmod +x site-artisan

# start up containers
if [ ! "$C" == "$1$2$3$4$5" ]; then
    ./site-up -c=$C
else
    ./site-up
fi

# If app exists already:
if [ -d "${PROJECT_DIR}/app" ]; then

    # using an existing laravel app
    ./site-ssh -h=web -c="cd /var/www/site/app && composer install"

else
    # creating laravel app by running the installer, create app (happens as root)
    ./site-ssh -h=web -c="cd /var/www/site/commands && . ./install-laravel-installer"
    ./site-ssh -h=web -c="cd /var/www/site/ && composer create-project --prefer-dist laravel/laravel=${LARAVEL_VERSION} app"

fi

# ensure good storage
./site-ssh -h=web -c='chmod 777 /var/www/site/app/storage -R'
./site-ssh -h=web -c='chmod 777 /var/www/site/app/bootstrap -R'

# get back to repo root and change app folder ownership
cd "${PROJECT_DIR}" && sudo chown -R $(whoami):$(id -gn $(whoami)) app/

# should we rename this readme
cd "${PROJECT_DIR}"
printf "===== README.md - Now that Install is completed, \n we are switching README.md to use PROJECT-README.md. Refer to INSTALL-README.md directly if you continue to need it.\n\n"
if [ -L README.md ] && [ -e README.md ]; then
    ln -sfn PROJECT-README.md README.md
fi

# set back to quick-laravel-guide/commands
cd "${CURRENT_DIR}"

# set .env up with db entries
./show-db-envvars
