#!/usr/bin/env bash

CMD_CAT="cat ../DockerLocal/env-custom.yml"
CMD_SWAP="sed -r 's/:\s/=/g'"

printf "Copy the following into app/.env to ensure artisan and your app connect to your database correctly.\n\n"
eval "${CMD_CAT} | ${CMD_SWAP} | sed -n '/\bDB_HOST\b/p'"
eval "${CMD_CAT} | ${CMD_SWAP} | sed -n '/\bDB_PORT\b/p'"
eval "${CMD_CAT} | ${CMD_SWAP} | sed -n '/\bDB_DATABASE\b/p'"
eval "${CMD_CAT} | ${CMD_SWAP} | sed -n '/\bDB_USERNAME\b/p'"
eval "${CMD_CAT} | ${CMD_SWAP} | sed -n '/\bDB_PASSWORD\b/p'"
