#!/usr/bin/env bash

# Store contents in file temporarily.
CMD_CAT=$(cat ../DockerLocal/env-custom.yml)
echo "${CMD_CAT}" > temp-env.yml

# Format from env[VAR]: something -> VAR=something
sed -i'.bak' 's/env\[\(.*\)]: /\1=/g;' temp-env.yml
rm "temp-env.yml.bak"

# Print out what needs to be copied
printf "===== COPY DB vars to app/.env - Copy the following into app/.env to ensure artisan and your app connect to your database correctly.\n\n"
eval "cat temp-env.yml | grep '^DB_HOST='"
eval "cat temp-env.yml | grep '^DB_PORT='"
eval "cat temp-env.yml | grep '^DB_DATABASE='"
eval "cat temp-env.yml | grep '^DB_USERNAME='"
eval "cat temp-env.yml | grep '^DB_PASSWORD='"

# Remove temp file
rm temp-env.yml
