#!/usr/bin/env bash

CURRENT_DIR=$(pwd)

# See if we are in DockerLocal/commands already (via symlink)
if [ ! -f  "site-ssh" ]; then
  DOCKERLOCAL_DIR=$(find DockerLocal/commands 2>/dev/null | head -n 1)
  printf "$DOCKERLOCAL_DIR\n"

  if [ -z "$DOCKERLOCAL_DIR" ]; then
      cd ../
      DOCKERLOCAL_DIR=$(find DockerLocal/commands 2>/dev/null | head -n 1)
      printf "$DOCKERLOCAL_DIR\n"
  fi

  cd "$DOCKERLOCAL_DIR"
fi

pwd

cd "$CURRENT_DIR"

if [ ! -f  "site-ssh" ]; then
  printf "Could not find DockerLocal Commands\n"
  exit
fi

WEB_SERVER_ROOT='/var/www/site/app'
WEB_SERVER_ROOT_FILE="../web-server-root"

if [ ! -f  "${WEB_SERVER_ROOT_FILE}" ]; then
  WEB_SERVER_ROOT=$(<$WEB_SERVER_ROOT_FILE)
fi

# using su, does not change home folder, throws errors with that
# ./site-ssh -h=web -c="cd ${WEB_SERVER_ROOT} && su -l www-data -s /bin/bash"

# using sudo, adjusts home folder properly
./site-ssh -h=web -c="cd ${WEB_SERVER_ROOT} && sudo -H -u www-data bash"
